logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO
            nodeValue: TRACE
    root: INFO
spring:
  cloud:
    gateway:
      routes:
        - id : discovery-server
          uri: http://localhost:8761
          filters: SetPath=/
          predicates: Path=/eureka/web
        - id: order-service
          uri: lb://order-service
          predicates: Path=/order/**
        - id: discovery-server-static
          predicates: Path=/eureka/**
          uri: http://localhost:8761
        - id: fulfilment-service
          predicates: Path=/test
          uri: lb://fulfilment-service
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka