eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
server:
  port: 8065


spring:
  application:
    name: fulfilment-service
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: careTopicId

    template:
      default-topic: orderTopic