spring:
  datasource:
    url: "jdbc:h2:mem:test;INIT=CREATE SCHEMA IF NOT EXISTS order_schema"
    driver-class-name: org.h2.Driver
    hikari:
      schema: order_schema
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
    show-sql: false
    properties:
      hibernate:
        default_schema: order_schema
        connection:
          url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS order_schema
        username: sa
        password:

